<?php
$text['title-reseller_dashboard']['en-us'] = "Reseller Dashboard";
$text['title-domain_statistics']['en-us'] = "Domain Statistics";
$text['button-export']['en-us'] = "Export";
$text['table-domain']['en-us'] = "Domain";
$text['table-pbx_users']['en-us'] = "PBX users";
$text['table-call_centers']['en-us'] = "Call centers";
$text['table-call_recordings']['en-us'] = "Call recordings";
$text['table-sip_trunks']['en-us'] = "SIP trunks";
$text['table-meeting_rooms']['en-us'] = "Meeting rooms";
$text['table-voicemail_trancriptions']['en-us'] = "Voicemail transcriptions";
$text['table-total']['en-us'] = "Total";
$text['title-graph']['en-us'] = "Reseller graph";
$text['graph-extension']['en-us'] = "Extensions";
$text['graph-user']['en-us'] = "Users";
$text['graph-destination']['en-us'] = "Destinations";
$text['graph-device']['en-us'] = "Devices";
$text['graph-queue']['en-us'] = "CC Queues";
$text['graph-voicemail']['en-us'] = "Voicemails";
